version: '3.6'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    volumes:
      - ./:/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - backend
networks:
  backend:
    driver: bridge
